services:
  db: # Base de datos
    image: postgres:16 # Imagen oficial de PostgreSQL
    environment: # Variables de entorno para configurar PostgreSQL
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Puerto de PC - Puerto del contenedor
    volumes:
      - postgres_data:/var/lib/postgresql/data # Esto es un 'volume' para persistir datos, la ruta es interna de PostgreSQL en el contenedor
    healthcheck: # Esto es para que Docker pueda verificar si la base de datos está lista para aceptar conexiones
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api: # API de FastAPI (Python)
    build: ./api # No es imagen oficial, se construye a partir del Dockerfile en ./api
    ports:
      - "8000:8000"
    environment: # Variables de entorno para configurar la conexión a la base de datos
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} 
    depends_on:
      db: # Esto significa que la API no intentar conectarse a la BDD hasta que el servicio de la base de datos esté listo
        condition: service_healthy # Esto hace que la API espere a que el healthcheck de la base de datos indique que está lista antes de iniciar
    volumes:
    # Esto dice basicamente:
    # "Todo lo que está en mi carpeta api/ de Windows, hacelo visible en /app dentro del contenedor"
      - ./api:/app # Esto es un 'bind mount' para que los cambios en el código de la API se reflejen inmediatamente en el contenedor (útil para desarrollo)
      # esto sobreescribe lo que COPY . . puso en el Dockerfile, pero es útil para desarrollo porque permite que los cambios en el código se reflejen inmediatamente sin tener que reconstruir la imagen cada vez
      # En producción no hay bind mount, entonces COPY . . es lo que manda y el código queda fijo dentro de la imagen.

  scanner: # Escaner de vulnerabilidades (Go)
    build: ./scanner # No es imagen oficial, se construye a partir del Dockerfile en ./scanner
    depends_on:
      db: # Esto significa que el escaner no intentará conectarse a la BDD hasta que el servicio de la base de datos esté listo
        condition: service_healthy # Esto hace que el escaner espere a que el healthcheck de la base de datos indique que está lista antes de iniciar

volumes:
  postgres_data: # Le digo a Docker que maneje este volumen


# COMENTARIOS PARA CLARIDAD

# Cada contenedor tiene su propio /app aislado. No comparten el mismo /app:
# Un container no sabe lo que hay en el otro, no pueden acceder a los archivos del otro. Esto es parte de la magia de Docker, cada contenedor es como una mini máquina virtual con su propio sistema de archivos, procesos, etc.

# Contenedor API          Contenedor Scanner
# ──────────────          ──────────────────
# /app/                   /app/
# ├── app/                └── bin/
# │   ├── main.py             scanner (binario)
# │   └── ...
# ├── tests/
# └── requirements.txt